import{a as L,S as b,i as c}from"./assets/vendor-Czlk9Ly7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="49290538-d7fd0606fc4d2d8ce4c897481",E="https://pixabay.com/api/",S=15;async function f(t,r=1){try{return(await L.get(E,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const u=document.querySelector(".gallery");let v=new b(".gallery a");function y(t,r=!1){if(r||(u.innerHTML=""),t.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}const n=t.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
        <p>Comments: ${s.comments}</p>
        <p>Downloads: ${s.downloads}</p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",n),v.refresh()}let l="",i=1,p=0;const P=15,q=document.querySelector(".form"),m=document.querySelector(".loader"),a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more");a.style.display="none";document.body.append(a);function h(){m.style.display="block"}function g(){m.style.display="none"}q.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!!l){i=1,h(),a.style.display="none";try{const r=await f(l,i);p=r.totalHits,y(r.hits),t.target.reset(),r.hits.length>0&&(a.style.display="block")}catch{c.error({title:"Error",message:"Failed to fetch images"})}finally{g()}}});a.addEventListener("click",async()=>{i+=1,h();try{const t=await f(l,i);y(t.hits,!0),i*P>=p&&(a.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),$()}catch{c.error({title:"Error",message:"Failed to load more images"})}finally{g()}});function $(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
