import{a as w,S as E,i as y}from"./assets/vendor-Czlk9Ly7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const S="49290538-d7fd0606fc4d2d8ce4c897481",q="https://pixabay.com/api/",v=15;async function m(t,r=1){try{return(await w.get(q,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const p=document.querySelector(".gallery");let P=new E(".gallery a");function h(t,r=!1){if(r||(p.innerHTML=""),t.length===0){y.error({title:"Error",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}const n=t.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
        <p>Comments: ${s.comments}</p>
        <p>Downloads: ${s.downloads}</p>
      </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",n),P.refresh()}let d="",c=1,g=0;const A=15,$=document.querySelector(".form"),l=document.querySelector(".loader"),a=document.querySelector(".load-more");a.textContent="Load more";a.classList.add("load-more");a.style.display="none";document.body.append(a);function L(){l.style.display="block"}function b(){l.style.display="none"}const f=100;let i=0;$.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements["search-text"].value.trim(),!!d){c=1,i=0,l.style.display="block",a.style.display="none",L();try{const r=await m(d,c);g=r.totalHits,h(r.hits),i+=r.hits.length,t.target.reset(),r.hits.length>0&&i<f&&(a.style.display="block")}catch{y.error({title:"Error",message:"Failed to fetch images"})}finally{l.style.display="none",b()}}});a.addEventListener("click",async()=>{if(!(i>=f)){c+=1,l.style.display="block",L();try{const t=await m(d,c);h(t.hits,!0),i+=t.hits.length,(i>=f||c*A>=g)&&(a.style.display="none",y.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),R()}catch{y.error({title:"Error",message:"Failed to load more images"})}finally{l.style.display="none",b()}}});function R(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
