import{a as b,S as E,i as c}from"./assets/vendor-Czlk9Ly7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const S="49290538-d7fd0606fc4d2d8ce4c897481",q="https://pixabay.com/api/",v=15;async function h(e,r=1){try{return(await b.get(q,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:r}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const m=document.querySelector(".gallery");let M=new E(".gallery a");function p(e,r=!1){if(r||(m.innerHTML=""),e.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}const a=e.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
        <p>Comments: ${s.comments}</p>
        <p>Downloads: ${s.downloads}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",a),M.refresh()}let l="",d=1,f=0;const y=100;let n=0;const A=document.querySelector(".form"),g=document.querySelector(".loader"),i=document.querySelector(".load-more");i.style.display="none";function L(){g.style.display="block"}function w(){g.style.display="none"}A.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements["search-text"].value.trim(),!!l){d=1,n=0,L(),i.style.display="none";try{const r=await h(l,d);f=r.totalHits,p(r.hits),n+=r.hits.length,e.target.reset(),r.hits.length>0&&n<Math.min(y,f)&&(i.style.display="block")}catch{c.error({title:"Error",message:"Failed to fetch images"})}finally{w()}}});i.addEventListener("click",async()=>{if(!(n>=Math.min(y,f))){d+=1,L();try{const e=await h(l,d);p(e.hits,!0),n+=e.hits.length,n>=Math.min(y,f)&&(i.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),I()}catch{c.error({title:"Error",message:"Failed to load more images"})}finally{w()}}});function I(){const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
